### ISSUE TITLE
0compile cant run on 64 bit windows

### ISSUE THREAD

**Issue by pmiess** [0install/0compile#10]
on windows 10 professional 64 bit I get the following error
```
C:\Users\pmiess>0compile --help
Running external solver...
[====================] Complete
Traceback (most recent call last):
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\0compile", line 22, in <module>
    import autocompile, setup, clean, copysrc, build, publish, gui, bugs, include_deps
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\autocompile.py", line 21, in <module>
    types = list(arch.machine_ranks.keys()))
    AssertionError: Build target machine type 'x86_64' is not supported on this platform; expected one of ['i486', 'i386', None]

```

**Comment by talex5** [comment]
It should be detected here: https://github.com/0install/0install/blob/b2.3/zeroinstall/injector/arch.py#L43

What does this say if you run it locally in Python?

```python
from win32process import IsWow64Process
print(IsWow64Process())
```

**Comment by pmiess** [comment]
'''
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32process import IsWow64Process
>>> print(IsWow64Process())
False
'''

**Comment by talex5** [comment]
@bastianeicher added that Wow64 code - maybe he knows how to fix it?

**Comment by bastianeicher** [comment]
That code wasn't quite right unfortunately. It only detected when a 32bit version of Python was running on a 64bit version of Windows.

I've improved/fixed this in 0install/0install#171.

**Comment by bastianeicher** [comment]
@talex5 Could you create a new release of the 2.3.x branch that contains this fix?

**Comment by talex5** [comment]
Done.

**Comment by bastianeicher** [comment]
@pmiess Does this fix the issue for you?

**Comment by pmiess** [comment]
@bastianeicher 
I did the following

1. downloaded the 0install 2.3.14 zip
2. extracted it
3.  added it as a second source for 0install 
4. set 0compile to use it it with --version-for <URL> 2.3.14

It does not post the error.
--version-for <URL> 2.3.13 does post

I'd say that if you added this implementation to the feed it would fix it.

**Comment by bastianeicher** [comment]
@pmiess Version 2.3.14 is already listed in the feed but not yet marked as "stable". So while the `--version-for ... 2.3.13` argument is still needed for now, manually downloading and extracting the archive and registering it as an additional feed should not be necessary.

@talex5 Could you mark as 2.3.13 as stable or would you prefer to wait a little longer?

**Comment by talex5** [comment]
Done!
