### ISSUE TITLE
No error if Python is not installed, fails at runtime

### ISSUE THREAD

**Issue by ysangkok** [0install/0compile#2]
After installation using 0alias, when I run `0install run 0compile`, I get `env: python: No such file or directory`. Are the 0compile sources missing an entry for this required dependency?

**Comment by talex5** [comment]
What version of 0install are you using to run it? `env` shouldn't be getting run unless 0install is *really* old.

With 0install 2.9, I get:

    $ 0install run 0compile --version
    info: 0install (OCaml version): verbose mode on                                                                                       
    info: Staleness of app /home/user/.config/0install.net/apps/0compile is 0 hours
    info: check_for_updates: need_solve = false, want_bg_update = false; unavailable_sels = false
    info: 0COMPILE_0PUBLISH=/home/user/.cache/0install.net/implementations/sha256new_H6C6UE3W6NBSIBATVESQ5YXSA4AKVVA7X3OCRXBEPZP24ET7R3IA/0publish
    info: 0COMPILE_ZEROINSTALL=/home/tal/Projects/zero-install/old-0install
    info: PYTHONPATH=/home/tal/Projects/zero-install/old-0install
    info: 0COMPILE_0INSTALL=/home/user/.cache/0install.net/injector/exec-c4e34a/0COMPILE_0INSTALL/0COMPILE_0INSTALL
    info: ZEROINSTALL_GPG=/home/user/.cache/0install.net/injector/exec-c4e34a/ZEROINSTALL_GPG/ZEROINSTALL_GPG
    info: ZEROINSTALL_GPG=/home/user/.cache/0install.net/injector/exec-c4e34a/ZEROINSTALL_GPG/ZEROINSTALL_GPG
    info: exec /usr/bin/python2.7 /home/tal/Projects/zero-install/0compile/0compile --version
    0compile (zero-install) 1.4
    Copyright (C) 2006 Thomas Leonard
    This program comes with ABSOLUTELY NO WARRANTY,
    to the extent permitted by law.
    You may redistribute copies of this program
    under the terms of the GNU General Public License.
    For more information about these matters, see the file named COPYING.



Notice that it does `exec /usr/bin/python2.7` to run Python directly, rather than running the script and using the `#!/usr/bin/env python` line.

**Comment by talex5** [comment]
Also, what version of 0compile did it pick? (use `0install show 0compile`)

Maybe it chose a really old version of that for some reason, before the Python dependency was explicit (maybe because it can't find Python). Try forcing it to pick 0compile 1.4 with:

    0install run --version=1.4 0compile --version

**Comment by ysangkok** [comment]
I am on FreeBSD.

`0install show 0compile`:

```
- URI: http://0install.net/2006/interfaces/0compile.xml
  Version: 0.23
  Path: /home/janus/.cache/0install.net/implementations/sha256=e94f0ed99293bb0b32cfd8f23795752f212cf76607b910a6aa79345e5b6f455e
  
  - URI: http://0install.net/2006/interfaces/0publish
    Version: 0.24
    Path: /home/janus/.cache/0install.net/implementations/sha256new_H6C6UE3W6NBSIBATVESQ5YXSA4AKVVA7X3OCRXBEPZP24ET7R3IA
    
    - URI: http://0install.net/2007/interfaces/ZeroInstall.xml
      Version: 0.54
      Path: /home/janus/.cache/0install.net/implementations/sha256=8e518cc08bfbd0477f9b274cfbbec2668e79fa82ec4e7b34d610f7ec8077df64
```

With `0install run --version=1.4 0compile --version` I get:

```
Can't find all required implementations:                                       
- http://0install.net/2006/interfaces/0compile.xml -> 1.4 (sha1new=f1034557f5d41c09bbffdc1bffee69dcff9c7a14)
    User requested version 1.4
- http://0install.net/2006/interfaces/0publish -> 0.24 (sha1new=078330f7f927f7c10a6d81cd913deb5903391ef2)
- http://0install.net/2007/interfaces/ZeroInstall.xml -> 2.3.5 (sha1new=6f4892dfcb947a03dd3b89f04b2d0650e871a060)
    http://0install.net/2006/interfaces/0compile.xml 1.4 requires version 2.1..
    http://0install.net/2006/interfaces/0compile.xml 1.4 requires '0install' command
- http://repo.roscidus.com/python/python -> 2.7.10.0 (package:host:python:2.7.10.0)
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.5 requires version 2.6..!3 | 3.2.2..
    http://repo.roscidus.com/python/python-gobject 2.28.6 requires distribution:host
- http://repo.roscidus.com/python/python-gobject -> 2.28.6 (package:host:python-gobject:2.28.6)
- http://repo.roscidus.com/security/gnupg -> (problem)
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.5 requires 'run' command
    No usable implementations:
      sha1new=4a3636d68e9a64fe2b0b20c480a1af2218830b60 (1.4.10-4): Not compatible with the requested OS type
      sha1new=7b41bfd5e28db2298adee2f5c93d3233b7d94842 (1.4.10-4): Not compatible with the requested OS type
      sha1new=af4d8a604323238a092e4ed3cae9372f9d3302c4 (1.4.9-3): Not compatible with the requested OS type
      sha1new=e868aac11bfab00c3f1c43f9780c757fb86e5819 (1.4.9-3): Not compatible with the requested OS type
```

I realize these problems are arise because I am using FreeBSD. I have only used 0install since the day before yesterday, but it seems there are basically no FreeBSD packages. This is fair enough, but I am wondering why 0install doesn't try to build the dependencies before giving up. This is what I know from Nix, if a package isn't available in the binary cache, it will be built (if I recall correctly).

**Comment by talex5** [comment]
OK, so it couldn't find gpg (which the newer versions require) and tried to run an older version of 0compile from before that dependency was explicit.

In theory, it should check for gpg in ports if /var/db/pkg exists and the names matches one of those on http://repo.roscidus.com/security/gnupg (FreeBSD isn't listed there, so it will try all of them). However, I'm not sure 0install's ports support has been tested since the rewrite into OCaml, so it's quite likely to be broken.

If gpg isn't in ports and there's no way for 0install to query for it, it is also possible to hard-code support in. There's already some code in the `Mac` module to do that:

https://github.com/0install/0install/blob/1a4086c46c5db0338adcfeb7c07c79041da21791/ocaml/zeroinstall/distro_impls.ml#L496

Regarding building from source, 0install can't compile anything until it has gpg to check download signatures. However, many packages don't currently provide source so it will likely be hard going even after getting this working...

**Comment by ysangkok** [comment]
FreeBSD has gotten a new package manager named pkgkg, with binary package support.
This is all I have:

    $ ls /var/db/pkg/
    FreeBSD.meta		local.sqlite		repo-FreeBSD.sqlite	vuln.xml

I guess 0install should ask using the `pkg` command which packages are installed? Should I add support for this in https://github.com/0install/0install/blob/master/ocaml/zeroinstall/distro_impls.ml ?

**Comment by ysangkok** [comment]
Here is some sample output:

```
$ pkg info gnupg
gnupg-2.1.8
Name           : gnupg
Version        : 2.1.8
Installed on   : Fri Oct  2 20:31:40 UTC 2015
Origin         : security/gnupg
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : security
Licenses       : LGPL3 and GPLv3
Maintainer     : kuriyama@FreeBSD.org
WWW            : http://www.gnupg.org/
Comment        : The GNU Privacy Guard
Options        :
	DOCS           : on
	GNUTLS         : on
	KDNS           : off
	LDAP           : off
	NLS            : on
	SCDAEMON       : off
	SUID_GPG       : off
Shared Libs required:
	libnpth.so.0
	libintl.so.8
	libassuan.so.0
	libksba.so.8
	libgpg-error.so.0
	libgnutls.so.28
	libgcrypt.so.20
Annotations    :
	cpe            : cpe:2.3:a:gnupg:gnupg:2.1.8:::::freebsd10:x64
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 7.53MiB
Description    :
GnuPG is a complete and free replacement for PGP.

Because it does not use the patented IDEA algorithm, it can be used
without any restrictions.  GnuPG is an RFC2440 (OpenPGP) compliant
application.

WWW: http://www.gnupg.org/
```

`pkg info` yields lines like:

```
gnupg-2.1.8                    The GNU Privacy Guard
```

**Comment by talex5** [comment]
If you could add support for this, that would be great! The code in `distro_impls.ml` isn't very clear (sorry!) so please ask if you need help...

**Comment by ysangkok** [comment]
I am looking for a module in that file, to base the FreeBSD version on. I am thinking I could base it on the Mac module, because it has an eager cache and doesn't reference PackageKit. It also involves parsing a text file.

What does the exclamation mark mean in `method!`? I can't find it in the OCaml documentation on syntax. Only as a prefix-operator, which makes little sense here.

Let me just check with you if I have understood the Mac module correctly:

1. `get_package_impls` is called, it queries the `cache`. But what is the `|>` operator? Where can I look it up? Is `darwin` a fallback (which means I can disregard it)?
1. the `cache` is generated using the `regenerate` function
1. the `regenerate` function loops over the output of `ports -v installed` and calls `add_entry` (passed to `regenerate`)

What is the Darwin part for? Is it if an executable path is needed for a given package that puts executables outside `$PATH`?

How would you roughly approach this? Here is my plan:

1. copy the Mac module, remove the Darwin part
1. change the parsing to work for FreeBSD
1. implement Darwin-like stuff if certain necessary executables can't be found, or are wrong (I could imagine it would be a problem if packages used BSD `make` instead of GNU `make`)

**Comment by talex5** [comment]
`method!` means that it overrides a method inherited from a superclass.

`|>` is a built-in: http://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html
It lets you write expressions in the form of pipelines rather than nested expressions (it just makes some expressions easier to read... once you know what it means anyway!).

Because MacPorts might or might not be present on OS X, there is a separate Darwin distribution for OS X core packages. Either Darwin is used alone, or both MacPorts and Darwin are combined (MacPort's `get_package_impls` includes the results from Darwin). Hopefully FreeBSD can do something simpler!

Yes, `regenerate` rebuilds the cache. There are three options here, depending on how fast the local package system is:

1. Rebuild the entire cache in one go (`Distro_cache.create_eager`). Use this if each query takes a long time but getting everything is relatively quick.

2. Populate the cache on demand (`Distro_cache.create_lazy`). Use this if queries are fairly quick.

3. Don't cache anything, or only cache in-memory in a hashtable. Use this if queries are very fast (e.g. reading a metadata file directly without spawning a subprocess).

Your approach sounds sensible. Which template you start from depends mostly on what kind of caching (if any) would be most appropriate.

**Comment by ysangkok** [comment]
@talex5 I have some initial support, but now that I am testing it, I get the make problems, and I realize that the make dependency is not hardcoded in 0install, it is in the feed. Would it be possible to add ot http://repo.roscidus.com/devel/make:

```
<package-implementation distributions="FreeBSD" main="/usr/local/bin/gmake" package="gmake"/>
```

(as already exists for MacPorts)

**Comment by talex5** [comment]
Done (BTW, repo.roscidus.com's Git repository is at https://github.com/0install/repo.roscidus.com)

**Comment by ysangkok** [comment]
Thanks. It seems to have worked in 0install, but somehow not in 0compile.

```
$ 0install run 0compile autocompile http://0install.net/tests/GNU-Hello.xml 
================= http://0install.net/tests/GNU-Hello.xml ==================

Selecting versions for GNU Hello...
                                                                                
Failed. Details of all components and versions considered:

make

3.81-8 (Linux-x86_64) : Unsupported OS
3.81-8 (Linux-i386) : Unsupported OS
3.81-5 (Linux-x86_64) : Unsupported OS
3.81-5 (Linux-i386) : Unsupported OS

GNU Hello

1.3 (*-src) : OK
1.3 (*-newbuild) : Not source code

End details

Can't find all required implementations:
- http://0install.net/tests/GNU-Hello.xml -> 1.3 (sha1=2aae32fd27d194167eac7eb611d7ce0983f83dd7)
- http://repo.roscidus.com/devel/make -> (problem)
    No usable implementations:
      sha1new=cfdba304764c3265a3e35db5abc0e3bf170048e2 (3.81-8): Unsupported OS
      sha1new=62aea41d2b6ecfbb1569f739d607a7f664e73b81 (3.81-8): Unsupported OS
      sha1new=fdc117f803c22a910e10b03caf43bd08efedc475 (3.81-5): Unsupported OS
      sha1new=78fd81f1743ffe1c29f1025d1898b48634a391be (3.81-5): Unsupported OS
```

And in 0install:

```
$ 0install select --source  http://0install.net/tests/GNU-Hello.xml --verbose
info: 0install (OCaml version): verbose mode on
info: Getting new selections for http://0install.net/tests/GNU-Hello.xml
- URI: http://0install.net/tests/GNU-Hello.xml#source
  Version: 1.3
  Path: (not cached)
  
  - URI: http://repo.roscidus.com/devel/make
    Version: 4.1-2
    Path: (package:pkgng:gmake:4.1-2:*)
```

The last line must mean that it recognizes my gmake package. So why does 0compile complain?

**Comment by talex5** [comment]
0compile still uses the old Python solver. There's a branch at https://github.com/0install/0compile/tree/use-ocaml that uses the OCaml solver for regular builds, so you should be able to test with that.

I haven't updated it for `autocompile` yet though (I was waiting for 0install 2.10, which has a nice built-in autocompile-solver exposed over the JSON API, but now that's released, so 0compile could be updated to use it).

**Comment by talex5** [comment]
For testing, you could also try:

    0install select --source  http://0install.net/tests/GNU-Hello.xml --xml > sels.xml
    0compile setup sels.xml

**Comment by ysangkok** [comment]
Ok, it seems to work if I do `cd sels`, `0install run 0compile build` and then `0launch gnu-hello-freebsd-x86_64/0install/feed.xml`. Is there anything else I should test before submitting a pull request for the FreeBSD package support?

**Comment by talex5** [comment]
A unit-test would be nice if you don't have one already. You can submit a PR even if it isn't ready for merging (just mark it as `[Tracking]` in the title). You can continue to update the branch after making the PR. That makes it easy for other people to see what you're doing and add comments.
