### ISSUE TITLE
ImportError running 0compile on windows

### ISSUE THREAD

**Issue by pmiess** [0install/0compile#3]
when I run 0compile on windows I get an error

C:\zeroinstall>0install run http://0install.net/2006/interfaces/0compile.xml
Traceback (most recent call last):
  File "C:\ProgramData\0install.net\implementations\sha256new_DRI2B34BA24I5WP4NJCHZ6F2RU6ZDGRULN4WEUZNLYX6RW6BAN2A\0compile", line 11, in <module>
    import gobject; gobject.threads_init()
ImportError: No module named gobject

If I add the following dependency it works.

      <requires interface="http://repo.roscidus.com/lib/gtk">;
        <environment insert="bin" name="PATH"/>
      </requires>

This is what we did for diffuse when it needed GTK for python-gtk.

**Comment by talex5** [comment]
Should be fixed now (thanks to @bastianeicher in https://github.com/0install/repo.roscidus.com/pull/103).
