### ISSUE TITLE
Add python-gobject dependency to feed

### ISSUE THREAD

**Issue by bastianeicher** [0install/0compile#4]
This needs to be added to the 0compile feed for #3 to be fully fixed:
```xml
<requires interface="http://repo.roscidus.com/python/python-gobject"/>
```

**Comment by talex5** [comment]
In http://0install.net/2007/interfaces/ZeroInstall.xml I see we have:

```xml
<requires interface="http://repo.roscidus.com/python/python-gobject" os="POSIX"/>
```

Should that `os` restriction be removed? Then 0compile would pick it up automatically (although giving it explicitly is fine too).

**Comment by bastianeicher** [comment]
Does the Python version of Zero Install have any code paths on Windows that might reference gobject?
If so, it'd probably be better to enable the reference there too, as you suggest.

**Comment by talex5** [comment]
Yes, it uses it for the core `tasks.py` module:

https://github.com/0install/0install/blob/v2.3.5/zeroinstall/support/tasks.py#L63

I've removed the POSIX restriction, so it should work now.

**Comment by talex5** [comment]
I've updated the repository feed now, as a work-around for https://sourceforge.net/p/zero-install/mailman/message/36482009/
